.github/workflows/lint.yml, admin/team.md, source/.eslintignore, source/.eslintrc.json, source/.gitignore, source/eslint.config.mjs, source/package-lock.json, source/package.json, source/testing/index.js
Resolves #<issue number>
- TODO
- TODO
TODO
=> Fix eslint testing

.github/workflows/lint.yml, source/.eslintignore, source/.eslintrc.json, source/.gitignore, source/eslint.config.mjs, source/package-lock.json, source/package.json, source/testing/index.js
Resolves "Linting and code style enforcement (may happen in pipeline and/or in editor)"
- Install ESLint
- Setup ESLint configurations
- Add scripts
- Create new workflow
- Tested files that are expected to pass and files that aren't to compare to actual result.
=> Test ESLint checker

package-lock.json, source/.eslintrc.json, source/eslint.config.mjs, source/lintCheck.js, source/package-lock.json, source/package.json, source/testing/index.js
Resolves "Linting and code style enforcement (may happen in pipeline and/or in editor)"
- Returned the eslint config to json formatting to include file highlighting
- Added additional rules to ensure consistency
- Tested files that are expected to pass and files that aren't to compare to actual result.
=> Update ESLint To Use JSON for Config

.github/workflows/testing.yaml
Resolves #30 
- Added `--passWithNoTests` to jest yaml file
- Made a PR with no tests and the GitHub Actions check passed
=> Fix jest tests failing when no tests present

source/header/index.html
Resolves #19 and Resolves #24
Added index.html:
- contains the HTML skeleton of the header
- Used LiveServer to see how the header looked.
Header as of 5/14/24:
=> full header skeleton

source/displayTasks/displayTasks.js, source/displayTasks/index.html, source/displayTasks/tasks.json
Resolves #20 
1. Each incomplete task has 2 buttons, one to check off the task and one to delete the task
2. Once the task is checked off it gets moved to the bottom along with the complete tasks, this section has the task description with a strike-through line and no other functionalities
3. For incomplete tasks, you can also edit the task description by double-clicking on the task and save by clicking away 
4. Currently working on finishing up the tag feature for the task components
- We used a live server to test different cases including the button functionalities for checking the task, deleting it, and clicking on the task to edit it
=> Trey + Ali task skeleton

source/server.js
Hot fix: Allow html files to be accessed not from root
=> Serve static html

.github/workflows/jsdocs.yml
Resolves JSDocs setup
- Created jsdocs.yml workflow file
- Handles building and deployment of JSDocs to GitHub Pages using https://github.com/marketplace/actions/jsdoc-action
- Creates gh-pages branch for deployment
Note: Requires creation of deploy key and deploy key secret to work
- Tested on an unrelated test repo
=> Add JSDocs deployment to workflow

source/index.html, source/server.js, source/snippetCreation/snippetCreation.css, source/snippetCreation/snippetCreation.js, source/starter.sql
Resolves #54
index.html
- added `<div id="snippets"> `
- includes all HTML elements involved in the snippets section of the dashboard
- added `<div id="alert">`
- used for alerts when copying an existing snippet or adding new snippets
snippetCreation/snippetCreation.css
- uses #25 for general frame of snippets section
- contains all CSS styling for snippets section
- also contains CSS for alert window
- TODO: adding snippets and alert window were not included in design; might need to consult design lead
snippetCreation/snippetCreation.js
- database functionality including uploading and retrieving
- creates HTML objects to display retrieved snippets
- able to copy code snippet to clipboard
- pop up to alert when snippet successfully added or copied
Used Docker and tested on local server.
- …
=> Dylan and Advaith / Snippet Functionality 

.github/workflows/jsdocs.yml, source/displayTasks/displayTasks.js, source/server.js, source/sideCalendar/sideCalendar.js, source/snippetCreation/snippetCreation.js, source/taskCompleted/taskCompleted.js
Resolves #93 
- Added examples to every function that takes in parameters
- Clean JSDoc comments to ensure consistency
- Added namespaces for components for JSDocs to group them in the documentation
- Tested the deployment of GitHub pages on this branch to determine the grouping and examples loads correctly
=> In-depth JSDoc Comments

source/index.html, source/server.js, source/taskBox/send_task.js, source/taskBox/taskbox.css
Resolves #95 
- Took off the extra task box and form
- pop up form for due date
- after enter /task command , change color
- test it locally using server and docker
=> 95 post to do with task box on bottom

source/index.html, source/package-lock.json, source/package.json, source/snippetCreation/snippetCreation.css, source/snippetCreation/snippetCreation.js
Resolves #102 
- Added the highligher.js library to be able to perform code highlighting based on type
- Allow snippets to parse new lines to allow for multi-line code
- Add scrolling when code is vertically large
- Allow parsing of HTML elements
- I tested various pieces of code of different sizes and languages to see if the code was formatted and copied to clipboard correctly.
=> Code snippet highlighting

source/index.html, source/taskBox/send_task.js, source/taskBox/taskbox.css
Resolves #117 
- Prevent the ability to send tasks without /task command
- Disable and style button to indicate invalid task command
- Add appearing tip when hovering the disabled button
- Add transitions for button and tip style for smoother visuals
- Tested different task commands and verified only the correct one passes
- Verify the styling remains consistent depending on condition
Invalid Task Command Button
Tip On Hover
Valid Task Button
=> [BUG] Empty task input

source/displayTasks/displayTasks.js, source/server.js, source/snippetCreation/snippetCreation.js, source/taskBox/taskbox.css
Resolves #107 
- In the update method of the observer, normalize the date to midnight to avoid any time zone issues
- locally server
=> Bug fix one day forward tasklist snippet

source/snippetCreation/snippetCreation.js
Resolves #109 
- Used URI encoding and decoding to make no symbols are lost when querying
- Replaced symbols that malformed URI
- Allow HTML input by replacing < and > symbols to prevent HTML injection
- I test the snippets with various symbols in various languages
- I pasted entire files and verified they appeared correctly
- I verified that the copy function has the same values as the snippets.
=> Bug snippet displaying null

source/about/about.html
Resolves #136 
- I added a link to the source directory to the dashboard button
- Tested on node server on database
(when hovering over dashboard button)
=> Add link to dashboard from dashboard button

source/header/header.css
Resolves #135 
- Fixed about us spacing so text is on one line
- Made about us responsive for different device widths
- Tested with node server on database
=> Fixed About us spacing and made responsive

source/taskBox/send_task.js
Resolves #127 
Added two lines to send_task.js that update the navbar
Used local server w/ Docker
Before adding task
Immediately after (no reload required)
=> Navbar update bugfix

source/taskBox/send_task.js
Resolves #126 
- Added two new functions to `taskBox/send_task.js` to track and set cursor position
- Cursor is no longer kicked to end of the line when typing
- Tested on node server with database
(I typed "middle" after typing "leftright")
=> Allow cursor moving in task input box

source/displayTasks/displayTasks.css
Resolves #147
Added a word-break styling to tasks in displayTasks.css
Local server
Before
After
=> Task text overflow bug

source/welcomePage/welcome.css, source/welcomePage/welcome.html, source/welcomePage/welcome.js
Resolves #75
1. I modified the welcome.html to match the Figma design
2. I added CSS styling in welcome.css to match the Figma design
3. I added a event listener in welcome.js to populate the fields (tasks to-do, tasks completed, streak, num of snippets) by fetching the data and processing it
- I tested it by running the server.js and fetching the data from the database
- Used live server too for the front end testing
=> Ali splash before dash (welcome page)

source/displayTasks/displayTasks.css, source/index.css
Resolves #116 
- I made changes to `index.css` and `displayTasks.css` to prevent elements from going off the page
- I modified the media query to allow scrolling on a smaller device
- Tested on node server with database
=> Fix dashboard not fitting in the window
